// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontagemCarga.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MontagemCarga.Infrastructure.Migrations
{
    [DbContext(typeof(MontagemCargaDbContext))]
    [Migration("20260306034018_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MontagemCarga.Domain.Entities.BlocoCarregamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bloco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CarregamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarregamentoId1")
                        .HasColumnType("uuid");

                    b.Property<int>("OrdemCarregamento")
                        .HasColumnType("integer");

                    b.Property<int>("OrdemEntrega")
                        .HasColumnType("integer");

                    b.Property<string>("PedidoIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarregamentoId");

                    b.HasIndex("CarregamentoId1");

                    b.ToTable("bloco_carregamentos", (string)null);
                });

            modelBuilder.Entity("MontagemCarga.Domain.Entities.Carregamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCarregamentoCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModeloVeicularId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroCarregamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PesoCarregamento")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("SituacaoCarregamento")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TipoDeCargaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoMontagemCarga")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TipoOperacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("carregamentos", (string)null);
                });

            modelBuilder.Entity("MontagemCarga.Domain.Entities.CarregamentoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarregamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarregamentoId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int?>("Pallet")
                        .HasColumnType("integer");

                    b.Property<string>("PedidoIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Peso")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("VolumeTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CarregamentoId");

                    b.HasIndex("CarregamentoId1");

                    b.ToTable("carregamento_pedidos", (string)null);
                });

            modelBuilder.Entity("MontagemCarga.Domain.Entities.BlocoCarregamento", b =>
                {
                    b.HasOne("MontagemCarga.Domain.Entities.Carregamento", null)
                        .WithMany("Blocos")
                        .HasForeignKey("CarregamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontagemCarga.Domain.Entities.Carregamento", "Carregamento")
                        .WithMany()
                        .HasForeignKey("CarregamentoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carregamento");
                });

            modelBuilder.Entity("MontagemCarga.Domain.Entities.CarregamentoPedido", b =>
                {
                    b.HasOne("MontagemCarga.Domain.Entities.Carregamento", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("CarregamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontagemCarga.Domain.Entities.Carregamento", "Carregamento")
                        .WithMany()
                        .HasForeignKey("CarregamentoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carregamento");
                });

            modelBuilder.Entity("MontagemCarga.Domain.Entities.Carregamento", b =>
                {
                    b.Navigation("Blocos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
